RDP-1484 convert all kafka offsets reset duration to positive value
transferwise/tw-tasks-executor pull request #178
Opened 2023-04-19 15:45 UTC by dattagiri

## Context
https://transferwise.atlassian.net/browse/RDP-1484
convert all kafka offsets reset duration to positive value

## Checklist
- [x] Change meets or does not compromise the [Baseline Security Requirements](https://transferwise.atlassian.net/wiki/spaces/EKB/pages/434929973/Baseline+Security+Requirements)

2023-04-25 09:59 UTC, tkornai requested changes

2023-04-25 09:59 UTC, tkornai commented on integration-tests/src/test/java/com/transferwise/tasks/triggering/SeekToDurationOnRebalanceListenerIntTest.java
> +    kafkaConsumer2.subscribe(Collections.singletonList(TOPIC), new SeekToDurationOnRebalanceListener(kafkaConsumer2, Duration.ofDays(-4).negated()));
```suggestion
    kafkaConsumer2.subscribe(Collections.singletonList(TOPIC), new SeekToDurationOnRebalanceListener(kafkaConsumer2, Duration.ofDays(4)));
```

2023-04-25 09:59 UTC, tkornai commented on integration-tests/src/test/java/com/transferwise/tasks/triggering/SeekToDurationOnRebalanceListenerIntTest.java
> +    // Second consumer to test the duration passed as negative number
Actually it is passed here as positive.

2023-04-25 11:03 UTC, tkornai submitted a review, later dismissed

2023-05-26 09:24 UTC, onukristo requested changes

2023-05-26 09:24 UTC, onukristo commented on integration-tests/src/test/resources/docker-compose.yml
> +    container_name: "zookeeper"
That name is used as a global unique identifier.
The value "zookeeper" is not unique enough and if some other service would use the same, we will get annoying conflicts.

Let's add "tw-tasks" prefix for all containers in this file.

2023-06-03 08:56 UTC, onukristo approved these changes

2023-06-05 12:06 UTC, merged