Use separate DAOs for Core/Test/Management
transferwise/tw-tasks-executor pull request #58
Opened 2020-10-17 14:55 UTC by yevhenii0

While the project consists of different modules all the data access operations are defined in core, while used by other places such as in tests or management modules. We can avoid accidental use of not efficient queries in prod by moving queries to the modules where they belong.

So we extract management queries to `SqlManagementDao`, tests queries to `SqlTestTaskDao`. Introduce a small abstraction around which table names and which types we use for dbs -> `DbConvention`. The whole logic be implemented without dbConvention but using more complex hierarchies, in this PR it's rather straightforward migration to separate classes.

Also a few small things
 - we don't use varargs while deriving query cache key, which means no need to create array of ints each time
 - we use bucket index instead of bucket size in a cache key, which I believe was a bug as each weight was expected to be < 3 bits

2020-10-27 19:00 UTC, onukristo requested changes
Pretty good.

CHANGELOG and version bump is needed.

Do we have a plan to start naming interfaces without "I" prefix? I don't mind, but we need to be consistent then.

We can not actually afford suboptimal management queries. Some small database with low resources have sometimes 40mln tasks in database and some full scan could create unwanted spikes.  But seems all the queries in JdbcManagementTaskDao are already optimal.

2020-10-27 22:21 UTC, yevhenii0 commented
Thanks.

Agree consistency is important, new interfaces have been prefixed with `I`.
Added changelog + increased version.

2020-10-28 07:10 UTC, onukristo commented on CHANGELOG.md
> +Users of `tw-tasks-core-test` need to configure `ITestTaskDao` in the test configuration
Seems like we may provide tw-tasks-core-test-spring-boot-starter in the future :)

2020-10-28 07:10 UTC, onukristo approved these changes

2020-10-29 09:23 UTC, merged